### ISSUE TITLE
Support for Sass?

### ISSUE THREAD

**Issue by mklemme** [mjmlio/mjml#463]
This is related to https://github.com/mjmlio/mjml/issues/462 for adding styles to the compiled document head.

Is there a way to add scss/sass support for this project? It would be nice to be able to have things like resets and basic global styling. I know you can use the `mjml-style` to import `css` files.

Here is what adding this could look like:

**reference the compiled css file in the mjml template**
```html
<mj-style>
  @import "global.css";
</mj-style>
```

**The scss file to be compiled into css**
```scss
$link_color: blue;
$link_color_hover: darken($link_color, 10%);

a {
  color: $link_color;
  &:hover {
    color: $link_color_hover
  }
}
```

These styles would then be inlined into the document.
