### ISSUE TITLE
Mobile/Desktop Hide

### ISSUE THREAD

**Issue by jamiefinlayson** [mjmlio/mjml#770]
Is there support for hiding/revealing content blocks on mobile/desktop, taking into account Outlook, Gmail and Android?

**Comment by Renjaminino** [comment]
If I am understanding correctly, you shouldn't have to do that in the compiled HTML, unless it's something very customized.

You could write something like this below in your mj-style tag within the mj-head:

`@media only screen and (max-width: 480px) {
        *[class~=hide_on_mobile] { display: none !important;}
      }`

And then inline, you would write:

`<mj-column css-class="hide_on_mobile">
            <mj-image src="http://www.google.com/google.png" padding="0" />
          </mj-column>`

I've done LITMUS testing on that simple snippet above, and it works on everything Outlook 2007+ without any extra post MJML injections.

Does that help?

**Comment by jamiefinlayson** [comment]
Thank you for writing back so quickly. I was having trouble with android and Gmail app ignoring display none. This sounds great. I'll have a look tomorrow thanks again!

Best
Jamie

**Comment by Renjaminino** [comment]
OH, I see.  I've done tests on gmail, and it works fine using this. :)

**Comment by jamiefinlayson** [comment]
Amazing I can't wait to have another try tomorrow. Thanks again, your app is great!

Best
Jamie

**Comment by Renjaminino** [comment]
Not my app, but thank you either way. 👍 - Sure love using it.

**Comment by iRyusa** [comment]
Hi here !

Following up on @Renjaminino answer, you should add media queries on desktop version instead of mobile. Most of mobile client doesn't support media queries.
And you can use a class selector instead of attribute selectors, some clients doesn't support it 

So  : 

```css
@media only screen and (max-width: 480px) { *[class~=hide_on_mobile] { display: none !important;} }
```
becomes : 

```css 
.hide_on_mobile { display: none !important;}
@media only screen and (min-width: 480px) { .hide_on_mobile { display: block !important;} }
```
